export const socketEvent = {
    SETUP : 'SETUP',
    connection : 'connection',
    CONNECTED : 'CONNECTED',
    TYPING : 'TYPING',
    STOP_TYPING : 'STOP_TYPING',
    MESSAGE_RECIEVED : 'MESSAGE_RECIEVED',
    JOIN_CHAT : 'JOIN_CHAT',
    NEW_MESSAGE : 'NEW_MESSAGE',
    UPDATE_USER_STATUS: 'UPDATE_USER_STATUS',
    GET_USER_STATUS: 'GET_USER_STATUS'
}

